# Generated by Django 5.1.3 on 2024-11-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='awards',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='cuisine',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='num_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='price_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='ranking_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='rating_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='review_rating_count',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='trip_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='write_review',
            field=models.URLField(blank=True, null=True),
        ),
    ]
